// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKuZNdriGvmjmKTJkofABcvGjESIWOaTY',
    appId: '1:1054669743140:web:bab27794e3cad5b4f7a4b1',
    messagingSenderId: '1054669743140',
    projectId: 'crime-7dc13',
    authDomain: 'crime-7dc13.firebaseapp.com',
    storageBucket: 'crime-7dc13.appspot.com',
    measurementId: 'G-3353FJEJPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSCiewB3uMypHgdvqI45BwplMBvfoGg80',
    appId: '1:1054669743140:android:05cb1b8c11d3636ef7a4b1',
    messagingSenderId: '1054669743140',
    projectId: 'crime-7dc13',
    storageBucket: 'crime-7dc13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3BZ017mm1ZIFZ4Ffmts6PM_ITLuGUOP8',
    appId: '1:1054669743140:ios:581a4d4bcbb3ac0ff7a4b1',
    messagingSenderId: '1054669743140',
    projectId: 'crime-7dc13',
    storageBucket: 'crime-7dc13.appspot.com',
    iosBundleId: 'com.example.crimeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3BZ017mm1ZIFZ4Ffmts6PM_ITLuGUOP8',
    appId: '1:1054669743140:ios:581a4d4bcbb3ac0ff7a4b1',
    messagingSenderId: '1054669743140',
    projectId: 'crime-7dc13',
    storageBucket: 'crime-7dc13.appspot.com',
    iosBundleId: 'com.example.crimeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKuZNdriGvmjmKTJkofABcvGjESIWOaTY',
    appId: '1:1054669743140:web:e17ef4b76514423cf7a4b1',
    messagingSenderId: '1054669743140',
    projectId: 'crime-7dc13',
    authDomain: 'crime-7dc13.firebaseapp.com',
    storageBucket: 'crime-7dc13.appspot.com',
    measurementId: 'G-CVCJXRJX9S',
  );

}